version: '3'
services:
  backend:
    container_name: backend_production
    tty: true
    stdin_open: true
    build: back-end
    command: bash -c "npm install && npm run dev"
    volumes:
      - ./back-end:/app-backend
    ports:
      - "3001:3001"
    depends_on:
      - database
    environment:
       # MYSQL_ADDON_DB: ${MYSQL_ADDON_DB}
      # MYSQL_ADDON_HOST: ${MYSQL_ADDON_HOST}
      # MYSQL_ADDON_PASSWORD: ${MYSQL_ADDON_PASSWORD}
      # MYSQL_ADDON_PORT: ${MYSQL_ADDON_PORT}
      # MYSQL_ADDON_URI:  ${MYSQL_ADDON_URI}
      # MYSQL_ADDON_USER: ${MYSQL_ADDON_USER}
      # MYSQL_ADDON_VERSION: ${MYSQL_ADDON_VERSION}
      MYSQLUSER: ${MYSQLUSER}
      MYSQLHOST: database
      MYSQLPASSWORD: ${MYSQLPASSWORD}
      MYSQLDATABASE: ${MYSQLDATABASE}
      MYSQLPORT:  ${MYSQLPORT}
      JWT_SECRET: ${JWT_SECRET}
      CALENDAR_ID: ${CALENDAR_ID}
  database:
    image: mysql:8.0.19
    container_name: database
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQLPASSWORD}