version: '3'
services:
  backend:
    container_name: backend_production
    tty: true
    stdin_open: true
    build: back-end
    command: bash -c "npm install && npm run dev"
    volumes:
      - ./back-end:/app-backend
    ports:
      - "3001:3001"
    depends_on:
      - database
    environment:
      MYSQLUSER: ${MYSQLUSER}
      MYSQLHOST: database
      MYSQLPASSWORD: ${MYSQLPASSWORD}
      MYSQLDATABASE: ${MYSQLDATABASE}
      MYSQLPORT:  ${MYSQLPORT}
      JWT_SECRET: ${JWT_SECRET}
  database:
    image: mysql:5.7
    container_name: database
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQLPASSWORD}