version: '3'
services:
  backend:
    container_name: backend_production
    tty: true
    stdin_open: true
    build: back-end
    command: bash -c "npm install && npm run dev"
    volumes:
      - ./back-end:/app-backend
    ports:
      - "3001:3001"
    depends_on:
      - database
    environment:
      MYSQLDATABASE: ${MYSQLDATABASE}
      MYSQLHOST: ${MYSQLHOST}
      MYSQLPASSWORD: ${MYSQLPASSWORD}
      MYSQLPORT: ${MYSQLPORT}
      MYSQLUSER:  ${MYSQLUSER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PRIVATE_URL: ${MYSQL_PRIVATE_URL}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_URL: ${MYSQL_URL}
      JWT_SECRET: ${JWT_SECRET}
      CALENDAR_ID: ${CALENDAR_ID}
  database:
    image: mysql:8.0.19
    container_name: database
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQLPASSWORD}